
- name: template env
  template:
    src: "{{ chart_path }}/values.j2"
    dest: "{{ chart_path }}/values.yaml"

- name: rename vars
  template:
    src: "service.env"
    dest: "{{ release_name }}.env"

- name: template vars
  template:
    src: "{{ release_name }}.env"
    dest: "/tmp/{{ release_name }}.env"

- name: create configmap
  shell: "kubectl create configmap test --from-env-file=/tmp/{{ release_name }}.env -n logging-test --dry-run -o=yaml | kubectl apply -f -"

- name: check helm release
  shell:  helm ls | grep {{ release_name }}-test
  register: output

- name: helm install
  shell: helm install --name {{ release_name }}-test {{ chart_path }}
  when: output.rc == 1

- name: helm install
  shell: helm upgrade --recreate-pods {{ release_name }}-test {{ chart_path }}
  #shell: helm template {{ chart_path }} > /tmp/test.yaml
